version: '3.1'

services:
    wordpress:
        container_name: wp
        image: wordpress
        restart: always
        ports:
            ['81:80']
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ${DB_USER}
            WORDPRESS_DB_PASSWORD: ${DB_PASS}
            WORDPRESS_DB_NAME: ${DB_NAME}
        volumes:
            - "${LOCAL_VOL_DATA}:/var/www/html"
    db:
        container_name: mysql
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - './db:/var/lib/mysql'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on: ['db']
        ports: ['82:80']
        links: ['db:db']
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: password
            UPLOAD_LIMIT: 1G
