version: '3.1'

services:
    wordpress:
        container_name: wp
        image: wordpress
        restart: always
        ports:
            ['81:80']
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ${DB_USER}
            WORDPRESS_DB_PASSWORD: ${DB_PASS}
            WORDPRESS_DB_NAME: ${DB_NAME}
        volumes:
            - "${LOCAL_VOL_WP_DATA}:/var/www/html"
            - "${LOCAL_VOL_CONFIG_1}:/usr/local/etc/php/conf.d/uploads.ini"
    db:
        container_name: mysql
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
        volumes:
            - '${LOCAL_VOL_DB_DATA}:/var/lib/mysql'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on: ['db']
        ports: ['80:80']
        links: ['db:db']
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_USER: ${DB_USER}
            PMA_PASSWORD: ${DB_PASS}
            UPLOAD_LIMIT: 1G
